uuid object imported on guake_app.py
uuid import was not transferred from old Guake 0.X to Guake3.
That causes errors when using dbus uuid related functions for example:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/home/agarzi/github/guake3/guake/guake/dbusiface.py", line 143, in execute_command_by_uuid
    self.guake.execute_command_by_uuid(tab_uuid, command)
  File "/home/agarzi/github/guake3/guake/guake/guake_app.py", line 558, in execute_command_by_uuid
    tab_uuid = uuid.UUID(tab_uuid)
NameError: name 'uuid' is not defined